name: neu
description: >
  A simple helper for generating outstanding neumorphic-conforming designs.
version: 0.1.1
repository: https://github.com/Zabadam/neu
issue_tracker: https://github.com/Zabadam/neu/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  spectrum: 0.2.1+1

dev_dependencies:

flutter: null
