name: neu
description: >


version: 0.1.0
repository: https://github.com/Zabadam/neu
issue_tracker: https://github.com/Zabadam/neu/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  spectrum:
    path: ../spectrum/

flutter: null
